
name: Flutter APK

on:
  workflow_dispatch:       # permite botón "Run workflow"
  push:
    branches: [ main ]     # se ejecuta cuando haces un commit en main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Ensure Android platform (generate android/ if missing)
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

      - name: Inject Android permissions into Manifest
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a \
<uses-permission android:name="android.permission.CAMERA"/>\
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />\
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\
<uses-permission android:name="android.permission.RECORD_AUDIO" />' $MANIFEST
          head -n 50 $MANIFEST

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
